#!/bin/bash

# Make DBUS applicaitons pass $DISPLAY
/etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# Notifications
clipcatd

# Screenshots
flameshot >/dev/null &

# Gaming optimisations
export LD_BIND_NOW=1

# Easyeffects - noise suppression system wide
easyeffects --gapplication-service &

# SSH
if ! pgrep -u "$USER" ssh-agent >/dev/null; then
  ssh-agent -t 1h >"$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [[ ! -f "$SSH_AUTH_SOCK" ]]; then
  source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi
eval $(ssh-agent)
ssh-add /home/luke/.ssh/id_rsa

# Enviroment variables
export EDITOR="nvim" &

# Display
XRANDR_SETUP_LOCATION=~/.screenlayout/default.sh
if [ -e "$XRANDR_SETUP_LOCATION" ]; then
  $XRANDR_SETUP_LOCATION
else
  xrandr --listactivemonitors | sed -rn 's/.*  ([A-Za-z]+-[0-9]+)$/\1/p' | xargs -I % sh -c 'xrandr --output % --rotate normal --mode 1920x1080 --pos 0x0'
fi
xset -dpms
xset s off
xrdb -merge $HOME/.Xresources

# Replay
gpu-screen-recorder -w DP-4 -c mp4 -q very_high -k auto -ac opus -f 60 -cursor yes -cr full -r 1200 -o /home/luke/Videos -a alsa_output.pci-0000_0c_00.3.analog-stereo.monitor | alsa_input.usb-0c76_USB_Headphone_Set-00.mono-fallback &

# Desktop stuff
slstatus &
picom &
feh --bg-fill --randomize $HOME/.local/installs/dwm/backgrounds/ &
exec /usr/local/bin/dwm
